# Generated by Django 4.1.2 on 2022-11-21 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_listing_category_alter_listing_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='categoriesCreated',
            new_name='categoriesName',
        ),
    ]
