# Generated by Django 4.1.2 on 2023-01-05 21:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_rename_categoriescreated_categories_categoriesname'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
