# Generated by Django 4.1.2 on 2023-01-05 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_remove_listing_starterbid_alter_listing_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='whichListing',
        ),
        migrations.AddField(
            model_name='listing',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.bid'),
        ),
    ]
